import { Open_Sans } from "next/font/google";
import "./globals.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { ClerkProvider } from "@clerk/nextjs";
import { CurrentQuestionProvider } from "@/providers/CurrentQuestionContext.js";
import { TimerProvider } from "@/providers/TimerContext";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

  return (
    <CurrentQuestionProvider>
      <TimerProvider>
        <ClerkProvider>
          <html lang="en">
            <body className={font.className}>{children}</body>
          </html>
        </ClerkProvider>
      </TimerProvider>
    </CurrentQuestionProvider>
  );
}
